language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

addons:
  artifacts:
    s3_region: "us-west-2"
    debug: true
    paths:
      - $TRAVIS_BUILD_DIR/build/main-macosx
      - $TRAVIS_BUILD_DIR/build/main-linux
